// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {serial} from '../models';

export function CloseAllPorts():Promise<void>;

export function CommandConsoleExecute(arg1:string,arg2:string):Promise<void>;

export function ScanPorts():Promise<Array<string>>;

export function SetCtx(arg1:context.Context):Promise<void>;

export function StartCommandConsoleListener(arg1:string,arg2:serial.Mode):Promise<void>;

export function StopAllListeners():Promise<void>;

export function StopCommandConsoleListener(arg1:string):Promise<void>;
