// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseAllPorts() {
  return window['go']['modemModule']['ModemModule']['CloseAllPorts']();
}

export function CommandConsoleExecute(arg1, arg2) {
  return window['go']['modemModule']['ModemModule']['CommandConsoleExecute'](arg1, arg2);
}

export function ScanPorts() {
  return window['go']['modemModule']['ModemModule']['ScanPorts']();
}

export function SetCtx(arg1) {
  return window['go']['modemModule']['ModemModule']['SetCtx'](arg1);
}

export function StartCommandConsoleListener(arg1, arg2) {
  return window['go']['modemModule']['ModemModule']['StartCommandConsoleListener'](arg1, arg2);
}

export function StopAllListeners() {
  return window['go']['modemModule']['ModemModule']['StopAllListeners']();
}

export function StopCommandConsoleListener(arg1) {
  return window['go']['modemModule']['ModemModule']['StopCommandConsoleListener'](arg1);
}
